/* eslint-disable sonarjs/no-duplicate-string */
export const projects = [
  {
    name: "Maxx Proxy Manager",
    desc: "A modern Android app to manage, test, and monitor HTTP/SOCKS5 proxies with one-tap connectivity checks, latency insights, geo details, and import/export support.",
    github: "https://github.com/Priyansu8603/Maxx-Proxy-Manager",
    demo: "https://example.com/maxx-proxy-manager-demo",
    preview: "/images/maxxProxyManager.png",
    tech: [
      "Kotlin",
      "Jetpack Compose",
      "MVVM",
      "Clean Architecture",
      "Hilt",
      "Room",
      "OkHttp",
    ],
    featured: true,
  },
  {
    name: "FitPro - End-Customer Android App",
    desc: "An end-customer Android app for a multi-tenant Supplement platform with secure auth, Health Supplements, Order workflows, Scan Qr codes, and delivery options.",
    github: "https://github.com/Priyansu8603/FitPro-Android",
    demo: "https://github.com/Priyansu8603/FitPro-Android",
    preview: "/images/Fitpro.png",
    tech: [
      "Kotlin",
      "Jetpack Compose",
      "Material 3",
      "MVVM",
      "Hilt",
      "Retrofit",
      "Coroutines",
    ],
    featured: true,
  },
  {
    name: "Running Tracker App",
    desc: "A fitness-focused Android app to track running activity and health stats with a clean UI and robust data flow built on modern Android architecture.",
    github: "https://github.com/Priyansu8603/running-tracker-app",
    demo: "https://github.com/Priyansu8603/running-tracker-app",
    preview: "https://example.com/running-tracker-preview.png",
    tech: [
      "Kotlin",
      "MVVM",
      "Dagger",
      "Room",
      "Retrofit",
      "Coroutines",
      "Flow",
    ],
    featured: false,
  },
  {
    name: "InByteNews",
    desc: "A modern Android news app that aggregates content sources, supports Firebase authentication, bookmarking, search, and theme-aware settings.",
    github: "https://github.com/Priyansu8603/InByteNews",
    demo: "https://github.com/Priyansu8603/InByteNews",
    preview: "https://example.com/inbytenews-preview.png",
    tech: [
      "Kotlin",
      "MVVM",
      "Dagger 2",
      "Retrofit",
      "Firebase",
      "DataStore",
      "Coroutines",
    ],
    featured: false,
  },
  {
    name: "App Usage Manager - Android App",
    desc: "Android application that tracks app usage on a child’s device, groups apps by category, applies daily screen-time limits, enforces restrictions, and integrates Ads controlled via Firebase Remote Config.",
    github: "https://github.com/Priyansu8603/AppUsage-Manager",
    demo: "https://github.com/Priyansu8603/AppUsage-Manager",
    preview: "/images/AppUsage.png",
    tech: [
      "Kotlin",
      "Navigation",
      "Firebase Remote Config",
      "WorkManager",
      "Room",
      "Google adMob",
    ],
    featured: true,
  },
  {
    name: "MyWorld Android App",
    desc: "A modular multi-feature Android application with dedicated modules for onboarding, home, messaging, camera, and profile powered by a scalable architecture.",
    github: "https://github.com/Priyansu8603/MyWorld",
    demo: "https://github.com/Priyansu8603/MyWorld",
    preview: "/images/MyWorld.png",
    tech: [
      "Kotlin",
      "Hilt",
      "Navigation",
      "Firebase",
      "Retrofit",
      "Room",
      "Modular Architecture",
    ],
    featured: true,
  },
];
